name: life_mon
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart:  ^0.64.0
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  rive: ^0.11.17
  shared_preferences: ^2.5.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/presentation/images/background.png
    - lib/presentation/images/maindish.svg
    - lib/presentation/images/other.svg
    - lib/presentation/images/sidedish.svg
    - lib/presentation/images/soup.svg
    - lib/presentation/images/vegetable.svg
    - lib/presentation/images/character1.riv
    - lib/presentation/images/character2.riv
    - lib/presentation/images/character3.riv
    - lib/presentation/images/background.png
    - lib/presentation/images/cat.riv
    - lib/presentation/images/mohu.riv
    - lib/presentation/images/character1_icon.png
    - lib/presentation/images/character2_icon.png
    - lib/presentation/images/character3_icon.png
    - lib/presentation/images/profilebar.svg